# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: SciBench 2023 Competition
subtitle: 
# email: william.lacava@childrens.harvard.edu 
description: >- # this means to ignore newlines until "baseurl:"
  Scientist-in-the-loop benchmark for symbolic regression
# twitter_username: w_la_cava
github_username:  jiangnanhugo
repository: "jiangnanhugo/scibench"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin:  "dirt" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
classes: wide
plugins:
  - jekyll-feed
  - jekyll-include-cache

domain: jiangnanhugo.github.io/scibench # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com


# breadcrumbs: true

defaults:
  # _docs
  - scope:
      path: ""
    values:
      sidebar:
        nav: "main"
      layout: single
      toc: true
      author_profile: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jiangnanhugo/scibench/"
    - label: "Cavalab"
      # icon: "fab fa-fw fa-ruler-combined" # doesn't work
      icon: "fas fa-microscope" 

# author:
#   bio: "Maintained by [@jiangnanhugo](https://github.com/jiangnanhugo) and many open-source contributors"
#   links:
#     - label: "GitHub Repo"
#       icon: "fab fa-fw fa-github"
#       # icon: "fa-light fa-chart-network" # doesn't work
#       url: "https://github.com/jiangnanhugo/scibench/"

atom_feed:
  hide: true
